- name: Set aseprite variables
  set_fact:
    aseprite_version: "1.3.15.3"
    aseprite_sha256: 4c204a19ca2861886f1e501743c97f77bb9655587c9e7095b4c0636f42dfcb71
    aseprite_install_dir: /opt/aseprite
    aseprite_download_dir: /tmp/aseprite-src
    aseprite_state_file: /opt/aseprite/.aseprite_version

- name: Check if aseprite version state file exists
  state:
    path: "{{ aseprite_state_file }}"
  register: aseprite_state

- name: Read current aseprite version from state file
  slurp:
    path: "{{ aseprite_state_file }}"
  register: aseprite_current_version
  when: aseprite_state.stat.exists

- name: Set rebuild flag
  set_fact:
    needs_rebuild: "{{ not aseprite_state.stat.exists or (aseprite_current_version.content | b64decode | trim) != aseprite_version }}"

- name: Remove old build if version changed
  file:
    path: "{{ aseprite_install_dir }}"
    state: absent
  when: needs_rebuild

- name: Recreate build directory if removed
  file:
    path: "{{ aseprite_install_dir }}"
    state: directory
    mode: '0755'
  when: needs_rebuild

- name: Download aseprite release zip
  get_url:
    url: "https://github.com/aseprite/aseprite/releases/download/v{{ aseprite_version }}/Aseprite-v{{ aseprite_version }}-Source.zip"
    dest: "{{ aseprite_download_dir }}/aseprite-{{ aseprite_version }}.zip"
    checksum: "sha256:{{ aseprite_sha256 }}"
    mode: '0644'
  when: needs_rebuild

- name: Extract aseprite zip
  unarchive:
    src: "{{ aseprite_download_dir }}/aseprite-{{ aseprite_version }}.zip"
    dest: "{{ aseprite_download_dir }}/aseprite-{{ aseprite_version }}-src"
    remote_src: yes
  when: needs_rebuild
  
# I don't know if this will work.
# The zip archive has a .gitmodules entry
# but it isn't a git repo.
- name: Clone submodules
  shell: |
    cd "{{ aseprite_download_dir }}/aseprite-{{ aseprite_version }}-src"
    git submodule update --init --recursive
  when: needs_rebuild

- name: Install build dependencies
  apt:
    name:
      - g++
      - cmake
      - ninja-build
      # Definitely missing others here.
    state: present
    update_cache: yes

- name: Build aseprite using build.sh
  shell: |
    cd "{{ aseprite_download_dir }}/aseprite-{{ aseprite_version }}-src"
    ./build.sh
  when: needs_rebuild
