- name: Build aseprite from source
  become: yes
  become_user: ansible-builder

  block:
    - name: Set aseprite variables
      set_fact:
        aseprite_version: "v1.3.15.3"
        aseprite_sha: f26ce6420802c5f8c4f88e843de5521a9fb1c860
        aseprite_install_dir: /home/ansible-builder/aseprite
        aseprite_state_file: /home/ansible-builder/aseprite/.aseprite_version

        skia_tag: "m124-08a5439a6b" # Tagged release for m124
        skia_sha: 08a5439a6be726021c1c1905d23ce298a3edc5e4
        skia_install_dir: /home/ansible-builder/skia-aseprite
        skia_state_file: /home/ansible-builder/skia-aseprite/.skia_version

        depot_tools_install_dir: /home/ansible-builder/depot_tools

    - name: Check if aseprite version state file exists
      stat:
        path: "{{ aseprite_state_file }}"
      register: aseprite_state

    - name: Read current aseprite version from state file
      slurp:
        path: "{{ aseprite_state_file }}"
      register: aseprite_current_version
      when: aseprite_state.stat.exists

    - name: Set rebuild flag
      set_fact:
        needs_rebuild: "{{ not aseprite_state.stat.exists or (aseprite_current_version.content | b64decode | trim) != aseprite_version }}"

    - name: Clone or checkout aseprite
      git:
        repo: "https://github.com/aseprite/aseprite.git"
        dest: "{{ aseprite_install_dir }}"
        version: "{{ aseprite_version }}"
        update: yes
        clone: yes
      register: git_checkout
      when: needs_rebuild

    - name: Verify SHA matches expected (for supply chain security)
      assert:
        that:
          - git_checkout.after == aseprite_sha
        fail_msg: "expected SHA {{ aseprite_sha }}, got {{ git_checkout.after }}"
      when: needs_rebuild

    - name: Update aseprite submodules
      command: git submodule update --init --recursive
      args:
        chdir: "{{ aseprite_install_dir }}"
      when: needs_rebuild

    - name: Install aseprite and skia build dependencies
      become: yes
      become_user: root # Explicitly need root due to outer 'become'.
      apt:
        name:
          - g++
          - cmake
          - ninja-build
          # Needed for skia specifically:
          - libfontconfig1-dev
          - libgl1-mesa-dev
        state: present
        update_cache: yes
      when: needs_rebuild

    - name: Clone or checkout (skia for aseprite)
      git:
        repo: "https://github.com/aseprite/skia.git"
        dest: "{{ skia_install_dir }}"
        version: "{{ skia_tag }}"
        update: yes
        clone: yes
      register: git_checkout
      when: needs_rebuild

    - name: Verify skia SHA matches expected (for supply chain security)
      assert:
        that:
          - git_checkout.after == skia_sha
        fail_msg: "expected SHA {{ skia_sha }}, got {{ git_checkout.after }}"
      when: needs_rebuild

    - name: Clone or checkout depot_tools
      git:
        repo: "https://chromium.googlesource.com/chromium/tools/depot_tools.git"
        dest: "{{ depot_tools_install_dir }}"
        version: "main"
        update: yes
        clone: yes
      when: needs_rebuild

    - name: Build skia
      command: |
        sh -c '
        "{{ depot_tools_install_dir }}"/gclient &&
        python3 tools/git-sync-deps &&
        python3 bin/fetch-ninja &&
        "{{ depot_tools_install_dir }}"/gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false" &&
        ninja -C out/Release-x64 skia modules'
      args:
        chdir: "{{ skia_install_dir }}"

    - name: Configure aseprite
      command: |
        sh -c '
        cmake -B "{{ aseprite_install_dir }}/build" -S "{{ aseprite_install_dir }}" -G Ninja \
         -DCMAKE_BUILD_TYPE=RelWithDebInfo \
         -DLAF_BACKEND=skia \
         -DSKIA_DIR="{{ skia_install_dir }}" \
         -DSKIA_LIBRARY_DIR="{{ skia_install_dir }}/out/Release-x64"
        '
      args:
        chdir: "{{ aseprite_install_dir }}"

    - name: Build aseprite
      command: cmake --build "{{ aseprite_install_dir }}/build" -- aseprite
      args:
        chdir: "{{ aseprite_install_dir }}"
      when: needs_rebuild
