- name: Install general packages with apt
  apt:
    name:
      # General utilities.
      - neovim
      - git
      - tree
      - htop
      - ffmpeg # Assists yt-dlp.

      # Specialized utilities.
      - dosbox-x # Some abandonware targeted for support.
    state: present
    update_cache: true

- name: Install PPA repositories and packages
  become: yes

  vars:
    ppa_repositories:
      # Graphics.
      - ppa:inkscape.dev/stable

      # For downloading tutorial/educational videos for offline use.
      - ppa:tomtomtom/yt-dlp
    packages_to_install:
      - inkscape
      - yt-dlp

  block:
    - name: Get Ubuntu base codename from os-release
      set_fact:
        ubuntu_codename: "{{ lookup('ini', 'UBUNTU_CODENAME type=properties file=/etc/os-release') }}"

    - name: Add PPA repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: yes
        codename: "{{ ubuntu_codename }}"
      loop: "{{ ppa_repositories }}"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install PPA packages
      apt:
        name: "{{ packages_to_install }}"
        state: present
        update_cache: yes

    - name: Autoremove after PPA packages
      apt:
        autoremove: yes

- name: Install Flatpak applications
  become: yes

  vars:
    flathub_apps:
      # Graphics.
      - org.gimp.GIMP
      - com.github.PintaProject.Pinta

      # Music.
      - org.famistudio.FamiStudio

      # Basic educational.
      - org.kde.gcompris
      - org.kde.ktouch
      - org.kde.marble

      # Programming educational.
      - org.kde.kturtle

  block:
    - name: Install flatpak applications
      community.general.flatpak:
        name: "{{ flathub_apps }}"
        state: present
        method: system

- name: Download Furnace Tracker
  include_tasks: furnace.yml

- name: Build aseprite
  include_tasks: aseprite.yml
