- name: Configure iptables to disallow internet access by default
  become: yes

  # vars need to come from host_vars file
  
  block:
    - name: Reset UFW to defaults
      ufw:
        state: reset
        force: yes

    - name: Set UFW policies to deny all.
      ufw:
        direction: "{{ item}}"
        policy: deny
      loop:
        - incoming
        - outgoing
        - routed

    - name: Allow loopback traffic
      ufw:
        rule: allow
        interface: lo
        direction: "{{ item }}"
      loop:
        - incoming
        - outgoing

    - name: Configure iptables for internet_users
      shell: |
        {% for user in internet_users %}
        iptables -I ufw-user-output -p tcp -m owner --uid-owner $(id -u {{ user }}) -j ACCEPT
        iptables -I ufw-user-output -p udp -m owner --uid-owner $(id -u {{ user }}) -j ACCEPT
        iptables -I ufw-user-output -p icmp -m owner --uid-owner $(id -u {{ user }}) -j ACCEPT
        {% endfor %}
      args:
        executable: /bin/bash
      changed_when: false

    - name: Make iptables rules persistent with UFW
      shell: ufw reload
      changed_when: false
