---
- name: Ensure required groups exist
  group:
    name: "{{ item }}"
    state: present
    loop: "{{ users | map(attribute='groups') | flatten | unique }}"
    when: users | length > 0

- name: Create users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) | join(',') }}"
    append: yes
    create_home: yes
    shell: /bin/bash
    state: present
  loop: "{{ users }}"
  when: users | length > 0

- name: Set user quotas
  command: >
    setquota -u "{{ item.name }}"
    "{{ item.quota_soft }}"
    "{{ item.quota_hard }}"
    0 0 /home
  loop: "{{ users }}"
  when: users | length > 0
  changed_when: false
