- name: Enable quotas on /home mount
  mount:
    path: /home
    src: /dev/vg-data/lv-home
    fstype: ext4
    opts: defaults,usrquota,grpquota
    state: mounted

- name: Remount /home to apply quota options
  command: mount -o remount /home
  changed_when: false

- name: Create quota files on /home
  command: quotacheck -cugm /home
  args:
    creates: /home/aquota.user

- name: Check if quotas are already enabled
  command: quotaon -p /home
  register: quota_status
  failed_when: false
  changed_when: false

- name: Enable quotas on /home
  command: quotaon /home
  when: "'is on' not in quota_status.stdout"
